# Generated by Django 5.2.7 on 2025-11-01 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INFO", "Informação"),
                            ("AVISO", "Aviso"),
                            ("SUCESSO", "Sucesso"),
                            ("ALERTA", "Alerta"),
                            ("ERRO", "Erro"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="URL para onde a notificação deve levar",
                        max_length=500,
                    ),
                ),
                ("lida", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
