# Generated by Django 5.2.7 on 2025-11-01 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0002_notificacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mensalidade",
            name="valor",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="valor_desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="valor_final",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="capacidade_maxima",
            field=models.IntegerField(
                default=20, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
