# Generated by Django 5.2.7 on 2025-11-06 17:06

import django.core.validators
import paginas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0003_alter_mensalidade_valor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="data_upload_video",
            field=models.DateTimeField(
                blank=True, help_text="Data do upload do vídeo", null=True
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Vídeo da aula (máximo 50MB). Formatos: MP4, WebM, AVI, MOV",
                null=True,
                upload_to=paginas.models.video_upload_path,
                validators=[
                    paginas.models.validate_video_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm", "avi", "mov"]
                    ),
                ],
            ),
        ),
    ]
