# Generated by Django 5.2.7 on 2025-11-06 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paginas", "0004_aula_data_upload_video_aula_video"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do evento (ex: Corpo e Som)", max_length=200
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, help_text="Descrição do evento"),
                ),
                (
                    "data_evento",
                    models.DateField(help_text="Data de realização do evento"),
                ),
                (
                    "hora_evento",
                    models.TimeField(
                        blank=True, help_text="Horário do evento", null=True
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, help_text="Local do evento", max_length=200
                    ),
                ),
                (
                    "valor_ingresso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor do ingresso",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "meta_vendas",
                    models.IntegerField(
                        default=0,
                        help_text="Meta de ingressos a serem vendidos",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "comissao_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentual de comissão por ingresso vendido (0-100%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Evento ativo para vendas"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem/banner do evento",
                        null=True,
                        upload_to="eventos/",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_evento", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="VendaIngresso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        help_text="Quantidade de ingressos vendidos",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "data_venda",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Data da venda"
                    ),
                ),
                (
                    "data_registro",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Data/hora do registro"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, help_text="Observações sobre a venda"),
                ),
                (
                    "confirmado",
                    models.BooleanField(
                        default=False, help_text="Venda confirmada pela administração"
                    ),
                ),
                (
                    "valor_comissao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor da comissão do vendedor",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="paginas.evento",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        help_text="Dançarino que realizou a venda",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas_ingressos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda de Ingresso",
                "verbose_name_plural": "Vendas de Ingressos",
                "ordering": ["-data_venda", "-data_registro"],
            },
        ),
    ]
