# Generated by Django 5.2.7 on 2025-11-12 04:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_evento_vendaingresso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoFinanceiroMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Selecione o primeiro dia do mês de referência', unique=True, verbose_name='Mês de Referência')),
                ('lucro_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de receitas/lucros no mês', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lucro Total')),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de despesas/gastos no mês', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gasto Total')),
                ('a_receber_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Total de valores pendentes a receber', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='A Receber Total')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações ou detalhes adicionais sobre o mês', null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_financeiros_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Resultado Financeiro Mensal',
                'verbose_name_plural': 'Resultados Financeiros Mensais',
                'ordering': ['-mes'],
                'indexes': [models.Index(fields=['-mes'], name='paginas_res_mes_83eb5b_idx')],
            },
        ),
    ]
