# Generated by Django 5.2.7 on 2025-11-12 04:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_resultadofinanceiromensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Viagem para São Paulo - Agosto/2025', max_length=200, verbose_name='Nome da Despesa')),
                ('descricao', models.CharField(help_text='Breve descrição (ex: Figurino completo para apresentação de Natal)', max_length=300, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('FIGURINO', 'Figurino'), ('VIAGEM', 'Viagem/Excursão'), ('APRESENTACAO', 'Apresentação/Evento'), ('ACESSORIO', 'Acessórios'), ('TRANSPORTE', 'Transporte'), ('ALIMENTACAO', 'Alimentação'), ('HOSPEDAGEM', 'Hospedagem'), ('MAQUIAGEM', 'Maquiagem/Caracterização'), ('CABELO', 'Cabelo/Penteado'), ('SAPATO', 'Sapatos/Calçados'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Categoria')),
                ('valor_previsto', models.DecimalField(decimal_places=2, default=0.0, help_text='Quanto você estima gastar', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Previsto')),
                ('valor_gasto', models.DecimalField(decimal_places=2, default=0.0, help_text='Quanto você já gastou', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Gasto')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('PAGO', 'Pago'), ('PARCIAL', 'Parcialmente Pago'), ('CANCELADO', 'Cancelado')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('data_prevista', models.DateField(help_text='Quando você prevê esta despesa (ex: data da viagem)', verbose_name='Data Prevista')),
                ('data_pagamento', models.DateField(blank=True, help_text='Quando você pagou ou vai pagar', null=True, verbose_name='Data do Pagamento')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações adicionais, lembretes, detalhes de parcelamento, etc.', null=True, verbose_name='Observações')),
                ('itens', models.TextField(blank=True, help_text='Lista de itens que compõem esta despesa (ex: vestido, sapato, maquiagem)', null=True, verbose_name='Itens')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aluno', models.ForeignKey(help_text='Aluno que registrou esta despesa', on_delete=django.db.models.deletion.CASCADE, related_name='despesas_pessoais', to='paginas.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(blank=True, help_text='Turma ou evento relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='paginas.turma', verbose_name='Turma Relacionada')),
            ],
            options={
                'verbose_name': 'Despesa do Aluno',
                'verbose_name_plural': 'Despesas dos Alunos',
                'ordering': ['-data_prevista', '-data_criacao'],
                'indexes': [models.Index(fields=['aluno', '-data_prevista'], name='paginas_des_aluno_i_715206_idx'), models.Index(fields=['status'], name='paginas_des_status_aa6862_idx'), models.Index(fields=['categoria'], name='paginas_des_categor_47c57d_idx')],
            },
        ),
    ]
