# Generated by Django 5.2.7 on 2025-11-13 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_despesaaluno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição da despesa', max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('salarios', 'Salários'), ('equipamentos', 'Equipamentos'), ('marketing', 'Marketing'), ('manutencao', 'Manutenção'), ('utilidades', 'Utilidades (água, luz, internet)'), ('outros', 'Outros')], max_length=50, verbose_name='Categoria')),
                ('centro_custo', models.CharField(choices=[('administrativo', 'Administrativo'), ('pedagogico', 'Pedagógico'), ('marketing', 'Marketing'), ('infraestrutura', 'Infraestrutura'), ('eventos', 'Eventos')], max_length=50, verbose_name='Centro de Custo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da Despesa')),
                ('responsavel', models.CharField(help_text='Nome do responsável pela despesa', max_length=100, verbose_name='Responsável')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20, verbose_name='Status de Aprovação')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('motivo_recusa', models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_aprovadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Despesa Administrativa',
                'verbose_name_plural': 'Despesas Administrativas',
                'ordering': ['-data', '-data_criacao'],
                'indexes': [models.Index(fields=['-data'], name='paginas_des_data_9afc5e_idx'), models.Index(fields=['status_aprovacao'], name='paginas_des_status__48011b_idx'), models.Index(fields=['categoria'], name='paginas_des_categor_dfeda0_idx'), models.Index(fields=['centro_custo'], name='paginas_des_centro__e52f22_idx')],
            },
        ),
    ]
