# Generated by Django 5.2.7 on 2025-11-13 20:52

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_despesaadministrativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesaadministrativa',
            options={'ordering': ['-data_vencimento', '-data_criacao'], 'verbose_name': 'Despesa Administrativa', 'verbose_name_plural': 'Despesas Administrativas'},
        ),
        migrations.RemoveIndex(
            model_name='despesaadministrativa',
            name='paginas_des_data_9afc5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='despesaadministrativa',
            name='paginas_des_status__48011b_idx',
        ),
        migrations.RemoveIndex(
            model_name='despesaadministrativa',
            name='paginas_des_centro__e52f22_idx',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='aprovado_por',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='motivo_recusa',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='status_aprovacao',
        ),
        migrations.RemoveField(
            model_name='despesaadministrativa',
            name='valor',
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Upload do comprovante de pagamento', null=True, upload_to='despesas_admin/comprovantes/', verbose_name='Comprovante'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Quando foi efetivamente pago', null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='data_vencimento',
            field=models.DateField(blank=True, help_text='Data limite para pagamento', null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='fornecedor',
            field=models.CharField(blank=True, help_text='Nome da empresa ou pessoa que receberá o pagamento', max_length=200, null=True, verbose_name='Fornecedor/Beneficiário'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='nome',
            field=models.CharField(default='Nova Despesa', help_text='Ex: Aluguel Janeiro 2025, Conta de Luz, Salário Professor João', max_length=200, verbose_name='Nome da Despesa'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número da nota fiscal, boleto, recibo, etc.', max_length=100, null=True, verbose_name='Nº do Documento'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, help_text='Se for parcelado, quantas parcelas?', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='parcela_atual',
            field=models.IntegerField(blank=True, help_text='Qual parcela é esta?', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcela Atual'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado'), ('PARCIAL', 'Parcialmente Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='tipo_pagamento',
            field=models.CharField(choices=[('FIXO', 'Fixo (Mensal)'), ('VARIAVEL', 'Variável'), ('UNICO', 'Único'), ('PARCELADO', 'Parcelado')], default='UNICO', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quanto já foi pago', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Pago'),
        ),
        migrations.AddField(
            model_name='despesaadministrativa',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total da despesa', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='categoria',
            field=models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('ENERGIA', 'Energia Elétrica'), ('AGUA', 'Água'), ('INTERNET', 'Internet/Telefone'), ('SALARIO', 'Salários'), ('EQUIPAMENTO', 'Equipamentos'), ('MANUTENCAO', 'Manutenção'), ('LIMPEZA', 'Limpeza'), ('MATERIAL', 'Material de Consumo'), ('MARKETING', 'Marketing/Publicidade'), ('IMPOSTOS', 'Impostos/Taxas'), ('SEGURO', 'Seguros'), ('TRANSPORTE', 'Transporte/Combustível'), ('ALIMENTACAO', 'Alimentação'), ('EVENTO', 'Eventos/Apresentações'), ('SOFTWARE', 'Software/Licenças'), ('JURIDICO', 'Jurídico/Contábil'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Detalhes sobre a despesa', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='despesaadministrativa',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Anotações adicionais, lembretes, condições especiais', null=True, verbose_name='Observações'),
        ),
        migrations.AddIndex(
            model_name='despesaadministrativa',
            index=models.Index(fields=['-data_vencimento'], name='paginas_des_data_ve_6bde13_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaadministrativa',
            index=models.Index(fields=['status'], name='paginas_des_status_948afa_idx'),
        ),
        migrations.AddIndex(
            model_name='despesaadministrativa',
            index=models.Index(fields=['tipo_pagamento'], name='paginas_des_tipo_pa_7d85b2_idx'),
        ),
    ]
