# Generated by Django 5.2.7 on 2025-11-13 21:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0009_alter_despesaadministrativa_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nova Entrada', help_text='Ex: Mensalidade João Silva - Janeiro 2025', max_length=200, verbose_name='Nome da Entrada')),
                ('categoria', models.CharField(choices=[('MENSALIDADE', 'Mensalidades'), ('INGRESSO', 'Venda de Ingressos'), ('PATROCINIO', 'Patrocínio'), ('DOACAO', 'Doação'), ('WORKSHOP', 'Workshop/Curso'), ('ALUGUEL_ESPACO', 'Aluguel de Espaço'), ('APRESENTACAO', 'Apresentação/Show'), ('MERCHANDISING', 'Venda de Produtos'), ('CONSULTA', 'Consultoria'), ('OUTRO', 'Outros')], default='OUTRO', max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, help_text='Detalhes sobre a entrada', null=True, verbose_name='Descrição')),
                ('pagador', models.CharField(blank=True, help_text='Nome da pessoa ou empresa que pagou', max_length=200, null=True, verbose_name='Pagador/Origem')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total esperado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, help_text='Quanto já foi recebido', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Recebido')),
                ('data_prevista', models.DateField(blank=True, help_text='Data esperada do recebimento', null=True, verbose_name='Data Prevista')),
                ('data_recebimento', models.DateField(blank=True, help_text='Quando foi efetivamente recebido', null=True, verbose_name='Data do Recebimento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('ATRASADO', 'Atrasado'), ('PARCIAL', 'Parcialmente Recebido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('forma_recebimento', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('BOLETO', 'Boleto'), ('CHEQUE', 'Cheque')], max_length=20, null=True, verbose_name='Forma de Recebimento')),
                ('numero_parcelas', models.IntegerField(blank=True, help_text='Se for parcelado, quantas parcelas?', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Parcelas')),
                ('parcela_atual', models.IntegerField(blank=True, help_text='Qual parcela é esta?', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parcela Atual')),
                ('numero_documento', models.CharField(blank=True, help_text='Número do recibo, nota fiscal, etc.', max_length=100, null=True, verbose_name='Nº do Documento')),
                ('comprovante', models.FileField(blank=True, help_text='Upload do comprovante de recebimento', null=True, upload_to='entradas_admin/comprovantes/', verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, help_text='Anotações adicionais', null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Entrada Financeira',
                'verbose_name_plural': 'Entradas Financeiras',
                'ordering': ['-data_prevista', '-data_criacao'],
                'indexes': [models.Index(fields=['-data_prevista'], name='paginas_ent_data_pr_28cd53_idx'), models.Index(fields=['status'], name='paginas_ent_status_defbfb_idx'), models.Index(fields=['categoria'], name='paginas_ent_categor_c230fe_idx')],
            },
        ),
    ]
