# Generated by Django 5.2.7 on 2025-11-28 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_googlecalendarcredential_created_at_and_more'),
        ('paginas', '0010_entradafinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_evento', to='paginas.aula')),
            ],
        ),
    ]
