# Generated by Django 5.2.7 on 2025-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_googlecalendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecalendarcredential',
            name='event_id',
        ),
    ]
