"""
Django settings for giro_dance project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Load environment variables from .env file

GOOGLE_CALENDAR_SECRET_PATH = os.path.join(BASE_DIR, config("GOOGLE_CALENDAR_SECRET_PATH"))
SITE_URL = ""

# Caminho para o arquivo .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# MERCADO PAGO
MP_PUBLIC_KEY = env("MP_PUBLIC_KEY")
MP_ACCESS_TOKEN = env("MP_ACCESS_TOKEN")
MP_WEBHOOK_URL = env("MP_WEBHOOK_URL")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO: Mover para variável de ambiente em produção
# Use: SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-key')
SECRET_KEY = "django-insecure-p6y9^dgkmyasld_c9=3i%()%x#f#k@++odxqap3@-dj)m0jui6"

# SECURITY WARNING: don't run with debug turned on in production!
# TODO: Mudar para False em produção
# Use: DEBUG = os.environ.get('DEBUG', 'False') == 'True'
DEBUG = True

#ALLOWED_HOSTS = ['129.146.67.23','localhost', 'girodnc.qzz.io','127.0.0.1', 'catherin-postoptic-noncontemporaneously.ngrok-free.dev']
ALLOWED_HOSTS = ['*']

STATIC_URL = '/static/'
# Application definition

API_EXPORT_TOKEN = os.environ.get("API_EXPORT_TOKEN")



INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "login",
    "paginas",
    "calendario",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "paginas.middleware.CSRFDebugMiddleware",  # Debug de CSRF e autenticação
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

ROOT_URLCONF = "giro_dance.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",        # Templates globais
            BASE_DIR / "painel_aluno",     # Templates do painel
            BASE_DIR / "Financeiro" / "HTML", # Templates financeiro
            BASE_DIR / "GIROHOME",         # Templates home
            BASE_DIR / "login" / "templates", # Templates login
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "giro_dance.wsgi.application"

CSRF_TRUSTED_ORIGINS = [
    "https://localhost:8000",
    "http://localhost:8000",
    "https://*.app.github.dev",
    "https://redesigned-journey-wrw794q6q94c5pqv-8000.app.github.dev",
    "https://girodnc.qzz.io",
    "http://girodnc.qzz.io",
    "http://129.146.67.23",
    "https://129.146.67.23",
    "https://catherin-postoptic-noncontemporaneously.ngrok-free.dev",
]

# Configurações adicionais de CSRF
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_COOKIE_DOMAIN = None  # None permite qualquer domínio em ALLOWED_HOSTS
CSRF_COOKIE_AGE = 31449600  # 1 ano em segundos (evita expiração frequente)

# Template customizado para erro CSRF
# O Django procura automaticamente por 403_csrf.html


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Destino do collectstatic (produção)

# Diretórios de arquivos estáticos para desenvolvimento
# Removido STATICFILES_DIRS - Django busca automaticamente em app/static/
# STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_COOKIE_NAME = "csrftoken"   # padrão
CSRF_USE_SESSIONS = False        # padrão - False para permitir upload de arquivos grandes
CSRF_COOKIE_SECURE = False       # True apenas se usar HTTPS em produção
CSRF_COOKIE_SAMESITE = 'Lax'     # Permite cookies em redirecionamentos
CSRF_COOKIE_HTTPONLY = False     # False para permitir JavaScript acessar se necessário

# Configurações de Sessão
SESSION_COOKIE_NAME = 'sessionid'  # Nome padrão do cookie de sessão
SESSION_COOKIE_SAMESITE = 'Lax'  # Configura o SameSite para sessões também
SESSION_COOKIE_SECURE = False    # True apenas se usar HTTPS em produção
SESSION_COOKIE_AGE = 1209600     # 2 semanas (evita expiração durante uso)
SESSION_SAVE_EVERY_REQUEST = False  # ALTERADO: False para não recriar sessão a cada request
SESSION_COOKIE_HTTPONLY = True   # Segurança: JavaScript não pode acessar o cookie de sessão
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Usa banco de dados para sessões

# girodnc_project/settings.py

# ... (resto do arquivo)

# Configurações de Mídia para Upload de Arquivos
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurações de upload de arquivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB em bytes
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB em bytes
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000    # Limite de campos no formulário

# Configurações de Login/Logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/painel/'
LOGOUT_REDIRECT_URL = '/login/'
