# Generated by Django 5.2.7 on 2025-10-25 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=20)),
                ("telefone_emergencia", models.CharField(max_length=20)),
                ("endereco", models.TextField()),
                ("data_matricula", models.DateField(auto_now_add=True)),
                ("ativo", models.BooleanField(default=True)),
                ("observacoes", models.TextField(blank=True)),
                ("foto", models.ImageField(blank=True, null=True, upload_to="alunos/")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aluno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aluno",
                "verbose_name_plural": "Alunos",
                "ordering": ["usuario__first_name", "usuario__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(blank=True, max_length=200)),
                ("conteudo", models.TextField()),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("lida", models.BooleanField(default=False)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_recebidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remetente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("BALLET", "Ballet"),
                            ("JAZZ", "Jazz"),
                            ("HIP_HOP", "Hip Hop"),
                            ("CONTEMPORANEO", "Contemporâneo"),
                            ("DANCA_SALAO", "Dança de Salão"),
                            ("ZUMBA", "Zumba"),
                            ("STREET_DANCE", "Street Dance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("INICIANTE", "Iniciante"),
                            ("INTERMEDIARIO", "Intermediário"),
                            ("AVANCADO", "Avançado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacidade_maxima", models.IntegerField(default=20)),
                ("ativa", models.BooleanField(default=True)),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "professor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turmas_professor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("conteudo", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("GERAL", "Geral"),
                            ("TURMA", "Turma Específica"),
                            ("ALUNO", "Aluno Específico"),
                            ("EVENTO", "Evento"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="GERAL",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_expiracao", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("importante", models.BooleanField(default=False)),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="painel_aluno_app.aluno",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avisos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="painel_aluno_app.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso",
                "verbose_name_plural": "Avisos",
                "ordering": ["-importante", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                ("tema", models.CharField(blank=True, max_length=200)),
                ("conteudo", models.TextField(blank=True)),
                ("realizada", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="painel_aluno_app.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["-data", "-hora_inicio"],
                "unique_together": {("turma", "data", "hora_inicio")},
            },
        ),
        migrations.AddField(
            model_name="aluno",
            name="turmas",
            field=models.ManyToManyField(
                blank=True, related_name="alunos", to="painel_aluno_app.turma"
            ),
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("FALTA", "Falta"),
                            ("FALTA_JUSTIFICADA", "Falta Justificada"),
                            ("ATESTADO", "Atestado"),
                        ],
                        default="PRESENTE",
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField(blank=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="painel_aluno_app.aluno",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frequencias",
                        to="painel_aluno_app.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frequência",
                "verbose_name_plural": "Frequências",
                "ordering": ["-aula__data"],
                "unique_together": {("aluno", "aula")},
            },
        ),
        migrations.CreateModel(
            name="Mensalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_referencia", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("valor_final", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_vencimento", models.DateField()),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("ATRASADO", "Atrasado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=50)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensalidades",
                        to="painel_aluno_app.aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade",
                "verbose_name_plural": "Mensalidades",
                "ordering": ["-mes_referencia"],
                "unique_together": {("aluno", "mes_referencia")},
            },
        ),
        migrations.CreateModel(
            name="HorarioAula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("SEG", "Segunda-feira"),
                            ("TER", "Terça-feira"),
                            ("QUA", "Quarta-feira"),
                            ("QUI", "Quinta-feira"),
                            ("SEX", "Sexta-feira"),
                            ("SAB", "Sábado"),
                            ("DOM", "Domingo"),
                        ],
                        max_length=3,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                ("sala", models.CharField(blank=True, max_length=50)),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="painel_aluno_app.turma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Aula",
                "verbose_name_plural": "Horários de Aulas",
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("turma", "dia_semana", "hora_inicio")},
            },
        ),
    ]
