# Generated by Django 5.2.7 on 2025-10-10 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("professor", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("falta", "Faltou"),
                            ("justificada", "Falta Justificada"),
                        ],
                        default="presente",
                        max_length=20,
                    ),
                ),
                ("marcado", models.BooleanField(default=False)),
                ("data_marcacao", models.DateTimeField(auto_now=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="painel_aluno_app.aula",
                    ),
                ),
            ],
            options={
                "unique_together": {("aluno", "aula")},
            },
        ),
    ]
