# Generated by Django 5.2.7 on 2025-10-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel_aluno_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="frequencia",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="frequencia",
            name="quantidade_falta",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="frequencia",
            name="aluno",
        ),
        migrations.RemoveField(
            model_name="frequencia",
            name="aula",
        ),
        migrations.RemoveField(
            model_name="frequencia",
            name="data_marcacao",
        ),
        migrations.RemoveField(
            model_name="frequencia",
            name="marcado",
        ),
        migrations.RemoveField(
            model_name="frequencia",
            name="status",
        ),
        migrations.DeleteModel(
            name="Aula",
        ),
    ]
